services:
  web:
    build: .
    container_name: carbon-assistant-app
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis-insight:
    image: redis/redisinsight:latest
    container_name: carbon-assistant-redisinsight
    ports:
      - "8001:5540"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: carbon-assistant-redis

  worker:
    build: .
    container_name: carbon-assistant-worker
    command: rq worker --with-scheduler -u redis://redis:6379/0
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis